- project:
    check:
      jobs:
        - thoth-coala
    gate:
      queue: thoth-station/core
      jobs:
        - thoth-coala
    release:
      jobs:
        - upload-pypi-sesheta
    kebechet-auto-gate:
      queue: thoth-station/core
      jobs:
        - thoth-coala
