---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: custom-pipeline
  labels:
    app: thoth-ci
spec:
  params:
    - name: git_ref
      type: string
    - name: git_ref_type
      type: string
    - name: repo_name
      type: string
    - name: repo_url
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image

  tasks:
    - name: solver-rhel-8-py38
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-rhel-8-py38
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-rhel-8-py38
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-rhel-8-py36
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-rhel-8-py36
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-rhel-8-py36
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-32-py38
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-32-py38
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-32-py38
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-32-py37
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-32-py37
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-32-py37
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-31-py38
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-31-py38
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-31-py38
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-31-py37
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-31-py37
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-31-py37
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-31-py36
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-31-py36
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-31-py36
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-30-py37
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-30-py37
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-30-py37
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-30-py36
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-30-py36
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-30-py36
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-29-py37
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-29-py37
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-29-py37
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-29-py36
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-29-py36
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-29-py36
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: solver-fedora-28-py36
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "thoth-station"
        - name: registry_project
          value: solver-fedora-28-py36
        - name: registry_secret
          value: "thoth-station-thoth-pusher-secret"
        - name: dockerfile
          value: dockerfile/Dockerfile.solver-fedora-28-py36
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
