---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: solver-any
  annotations:
    thoth-station.ninja/template-version: 0.6.1
  labels:
    app: thoth
    component: solver
spec:
  templates:
    - name: solve
      inputs:
        parameters:
          - name: "THOTH_SOLVER_NAME"
          - name: "THOTH_SOLVER_DOCUMENT_ID"
          - name: "THOTH_LOG_SOLVER"
          - name: "THOTH_SOLVER_NO_TRANSITIVE"
          - name: "THOTH_SOLVER_PACKAGES"
          - name: "THOTH_SOLVER_INDEXES"
          - name: "IMAGE_STREAM_REGISTRY"
          - name: "IMAGE_STREAM_NAMESPACE"
          - name: "IMAGE_STREAM_TAG"
          - name: "THOTH_S3_ENDPOINT_URL"
          - name: "THOTH_CEPH_BUCKET_NAME"
          - name: "THOTH_CEPH_BUCKET_PREFIX"
          - name: "THOTH_DEPLOYMENT_NAME"
      outputs:
        artifacts:
          - name: outputdocument
            path: "/mnt/workdir/{{inputs.parameters.THOTH_SOLVER_DOCUMENT_ID}}"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.THOTH_CEPH_BUCKET_PREFIX}}/\
              {{inputs.parameters.THOTH_DEPLOYMENT_NAME}}/\
              solver/{{inputs.parameters.THOTH_SOLVER_DOCUMENT_ID}}"
              endpoint: "{{inputs.parameters.THOTH_S3_ENDPOINT_URL}}"
              bucket: "{{inputs.parameters.THOTH_CEPH_BUCKET_NAME}}"
              insecure: true
              accessKeySecret:
                name: argo-artifact-repository-secrets
                key: accessKey
              secretKeySecret:
                name: argo-artifact-repository-secrets
                key: secretKey
      container:
        name: solver
        image: "{{inputs.parameters.IMAGE_STREAM_REGISTRY}}/\
        {{inputs.parameters.IMAGE_STREAM_NAMESPACE}}/\
        {{inputs.parameters.THOTH_SOLVER_NAME}}:{{inputs.parameters.IMAGE_STREAM_TAG}}"
        env:
          - name: THOTH_SOLVER
            value: "{{inputs.parameters.THOTH_SOLVER_NAME}}"
          - name: THOTH_SOLVER_VIRTUALENV
            value: "/home/solver/venv"
          - name: THOTH_LOG_SOLVER
            value: "{{inputs.parameters.THOTH_LOG_SOLVER}}"
          - name: THOTH_SOLVER_NO_TRANSITIVE
            value: "{{inputs.parameters.THOTH_SOLVER_NO_TRANSITIVE}}"
          - name: THOTH_SOLVER_PACKAGES
            value: "{{inputs.parameters.THOTH_SOLVER_PACKAGES}}"
          - name: THOTH_SOLVER_OUTPUT
            value: "/mnt/workdir/{{inputs.parameters.THOTH_SOLVER_DOCUMENT_ID}}"
          - name: THOTH_SOLVER_INDEXES
            value: "{{inputs.parameters.THOTH_SOLVER_INDEXES}}"
          - name: "THOTH_DOCUMENT_ID"
            value: "{{inputs.parameters.THOTH_SOLVER_DOCUMENT_ID}}"
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                key: storage-bucket-name
                name: thoth
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        activeDeadlineSeconds: 1800
