FROM fedora:31
ENV \
 LANG=en_US.UTF-8 \
 THOTH_SOLVER_TMP_DIR='/tmp/thoth-solver-install'

RUN \
  useradd -m solver && \
  dnf update --setopt=tsflags=nodocs -y && \
  dnf install --setopt=tsflags=nodocs -y python36 wget && \
  wget https://bootstrap.pypa.io/get-pip.py && \
  /usr/bin/python3.6 get-pip.py &&\
  mkdir -p ${THOTH_SOLVER_TMP_DIR}

# Install thoth-solver itself
COPY ./ ${THOTH_SOLVER_TMP_DIR}
RUN \
  cd ${THOTH_SOLVER_TMP_DIR} &&\
  /usr/bin/python3.6 -m pip install . &&\
  cd / &&\
  rm -rf ${THOTH_SOLVER_TMP_DIR} &&\
  unset THOTH_SOLVER_TMP_DIR &&\
  dnf clean all &&\
  virtualenv -p python3.6 /home/solver/venv &&\
  /home/solver/venv/bin/python3 -m pip install pipdeptree &&\
  chmod 777 -R /home/solver

WORKDIR /home/solver
USER solver

ENTRYPOINT ["thoth-solver"]
CMD ["python"]
