FROM quay.io/thoth-station/s2i-thoth-f32-py38:v0.23.2

ENV \
  LANG=en_US.UTF-8 \
  THOTH_SOLVER_TMP_DIR='/tmp/thoth-solver-install'

RUN \
  useradd -m solver && \
  dnf install --setopt=tsflags=nodocs -y pip && \
  dnf update --setopt=tsflags=nodocs -y && \
  mkdir -p ${THOTH_SOLVER_TMP_DIR}

# Install thoth-solver itself
COPY ./ ${THOTH_SOLVER_TMP_DIR}
RUN \
  cd ${THOTH_SOLVER_TMP_DIR} &&\
  pip install . &&\
  cd / &&\
  rm -rf ${THOTH_SOLVER_TMP_DIR} &&\
  unset THOTH_SOLVER_TMP_DIR &&\
  dnf clean all &&\
  virtualenv -p python3.8 /home/solver/venv &&\
  /home/solver/venv/bin/python3 -m pip install pipdeptree &&\
  chmod 777 -R /home/solver

WORKDIR /home/solver
USER solver

ENTRYPOINT ["thoth-solver"]
CMD ["python"]
