---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: solver-rhel-8.0-py36-
  annotations:
    thoth-station.ninja/template-version: 0.10.0-dev
  labels:
    app: thoth
    component: solver
    solver-type: solver-rhel-8.0-py36
spec:
  serviceAccountName: argo

  entrypoint: solve-and-sync
  # onExit: collect-outputs
  arguments:
    parameters:
      - name: THOTH_LOG_SOLVER
        value: "1"
      - name: THOTH_SOLVER_NO_TRANSITIVE
        value: "2"
      - name: THOTH_SOLVER_PACKAGES
        value: "3"
      - name: THOTH_SOLVER_OUTPUT
        value: "4"
      - name: THOTH_SOLVER_INDEXES
        value: "5"
      - name: THOTH_SYNC_DOCUMENT_ID
        value: "7"
      - name: THOTH_FORCE_SYNC
        value: "1"

  volumes:
    - name: outputs
      emptyDir: {}

  templates:
    - name: solve-and-sync
      dag:
        tasks:
          - name: solve
            templateRef:
              name: solver
              template: solve
            arguments:
              parameters:
                - name: THOTH_LOG_SOLVER
                  value: "{{workflow.parameters.THOTH_LOG_SOLVER}}"
                - name: THOTH_SOLVER_NO_TRANSITIVE
                  value: "{{workflow.parameters.THOTH_SOLVER_NO_TRANSITIVE}}"
                - name: THOTH_SOLVER_PACKAGES
                  value: "{{workflow.parameters.THOTH_SOLVER_PACKAGES}}"
                - name: THOTH_SOLVER_OUTPUT
                  value: "{{workflow.parameters.THOTH_SOLVER_OUTPUT}}"
                - name: THOTH_SOLVER_INDEXES
                  value: "{{workflow.parameters.THOTH_SOLVER_INDEXES}}"

          - name: graph-sync
            dependencies:
              - solve
            templateRef:
              name: graph-sync
              template: solver
            arguments:
              parameters:
                - name: THOTH_SYNC_DOCUMENT_ID
                  value: "{{workflow.parameters.THOTH_SYNC_DOCUMENT_ID}}"
                - name: THOTH_FORCE_SYNC
                  value: "{{workflow.parameters.THOTH_FORCE_SYNC}}"
