apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: solver
  annotations:
    description: "Thoth: Solver Job Template"
    openshift.io/display-name: "Thoth: Solver"
    version: 0.2.1
    tags: thoth,ai-stacks,aistacks,solver,machinlearning
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run solvers in Thoth, it is used
      to create new OpenShift Jobs running the analyzer.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: solver
    app: thoth
    component: solver

parameters:
  - name: THOTH_SOLVER_WORKFLOW_ID
    description: "a UUID for the workflow instance"
    displayName: "Workflow UUID"
    required: true
  - name: THOTH_SOLVER_NAME
    description: "Name of the solver to be used, for example: solver-rhel-8.0-py37"
    displayName: "Solver Name"
    required: true
  - name: THOTH_SOLVER_PACKAGES
    description: "Packages to be resolved"
    displayName: "Packages to be analyzed by solver"
    required: true
  - name: THOTH_SOLVER_NO_TRANSITIVE
    description: "Do not resolve transitive dependencies"
    displayName: "No transitive dependencies"
    required: true
  - name: THOTH_SOLVER_INDEXES
    description: "A comma separated list of indexes to scan during solver run"
    displayName: "Python Package Indexes"
    value: ""
  - name: THOTH_FORCE_SYNC
    description: Perform force sync - sync data even if they are reported to be existing
    displayName: Perform force sync
    required: true
    value: "0"
  - name: THOTH_LOG_SOLVER
    description: "Log solver actions"
    displayName: "Log solver actions"
    required: true
    value: INFO

  - name: IMAGE_STREAM_REGISTRY
    description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    value: "docker-registry.default.svc:5000"
  - name: IMAGE_STREAM_NAMESPACE
    description: Namespace the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    value: "thoth-infra-stage"
  - name: IMAGE_STREAM_TAG
    description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    value: "latest"

objects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      name: "${THOTH_SOLVER_WORKFLOW_ID}"
      annotations:
        thoth-station.ninja/template-version: 0.2.1
      labels:
        app: thoth
        component: solver
    spec:
      serviceAccountName: argo
      ttlStrategy:
        secondsAfterSuccess: 900 # Keep solver workflow available for 15 minutes
        # secondsAfterFailure kept unset to keep failed solvers, solvers should never fail.
      entrypoint: solve-and-sync
      arguments:
        parameters:
          - name: "THOTH_SOLVER_NAME"
            value: "${THOTH_SOLVER_NAME}"
          - name: "THOTH_SOLVER_WORKFLOW_ID"
            value: "${THOTH_SOLVER_WORKFLOW_ID}"
          - name: "THOTH_LOG_SOLVER"
            value: "${THOTH_LOG_SOLVER}"
          - name: "THOTH_SOLVER_NO_TRANSITIVE"
            value: "${THOTH_SOLVER_NO_TRANSITIVE}"
          - name: "THOTH_SOLVER_PACKAGES"
            value: "${THOTH_SOLVER_PACKAGES}"
          - name: "THOTH_SOLVER_INDEXES"
            value: "${THOTH_SOLVER_INDEXES}"
          - name: "THOTH_FORCE_SYNC"
            value: "${THOTH_FORCE_SYNC}"
          - name: "IMAGE_STREAM_REGISTRY"
            value: "${IMAGE_STREAM_REGISTRY}"
          - name: "IMAGE_STREAM_NAMESPACE"
            value: "${IMAGE_STREAM_NAMESPACE}"
          - name: "IMAGE_STREAM_TAG"
            value: "${IMAGE_STREAM_TAG}"
          - name: ceph_bucket_prefix
          - name: ceph_bucket_name
          - name: ceph_host
          - name: deployment_name
      volumes:
        - name: workdir
          emptyDir: {}
        - name: output
          emptyDir: {}
      templates:
        - name: "solve-and-sync"
          archiveLocation:
            archiveLogs: true
          dag:
            tasks:
              - name: "solverany"
                templateRef:
                  name: "solver-any"
                  template: "solve"
                arguments:
                  parameters:
                    - name: "THOTH_SOLVER_NAME"
                      value: "{{workflow.parameters.THOTH_SOLVER_NAME}}"
                    - name: "THOTH_SOLVER_DOCUMENT_ID"
                      value: "{{workflow.parameters.THOTH_SOLVER_WORKFLOW_ID}}"
                    - name: "THOTH_LOG_SOLVER"
                      value: "{{workflow.parameters.THOTH_LOG_SOLVER}}"
                    - name: "THOTH_SOLVER_NO_TRANSITIVE"
                      value: "{{workflow.parameters.THOTH_SOLVER_NO_TRANSITIVE}}"
                    - name: "THOTH_SOLVER_PACKAGES"
                      value: "{{workflow.parameters.THOTH_SOLVER_PACKAGES}}"
                    - name: "THOTH_SOLVER_INDEXES"
                      value: "{{workflow.parameters.THOTH_SOLVER_INDEXES}}"
                    - name: "IMAGE_STREAM_REGISTRY"
                      value: "{{workflow.parameters.IMAGE_STREAM_REGISTRY}}"
                    - name: "IMAGE_STREAM_NAMESPACE"
                      value: "{{workflow.parameters.IMAGE_STREAM_NAMESPACE}}"
                    - name: "IMAGE_STREAM_TAG"
                      value: "{{workflow.parameters.IMAGE_STREAM_TAG}}"
                    - name: "THOTH_S3_ENDPOINT_URL"
                      value: "{{workflow.parameters.ceph_host}}"
                    - name: "THOTH_CEPH_BUCKET_NAME"
                      value: "{{workflow.parameters.ceph_bucket_name}}"
                    - name: "THOTH_CEPH_BUCKET_PREFIX"
                      value: "{{workflow.parameters.ceph_bucket_prefix}}"
                    - name: "THOTH_DEPLOYMENT_NAME"
                      value: "{{workflow.parameters.deployment_name}}"

              - name: "graph-sync-solverany"
                dependencies:
                  - "solverany"
                templateRef:
                  name: "graph-sync"
                  template: "graph-sync"
                arguments:
                  artifacts:
                    - name: outputdocument
                      from: "{{tasks.solverany.outputs.artifacts.outputdocument}}"
                  parameters:
                    - name: "THOTH_DOCUMENT_ID"
                      value: "{{workflow.parameters.THOTH_SOLVER_WORKFLOW_ID}}"
                    - name: "THOTH_FORCE_SYNC"
                      value: "{{workflow.parameters.THOTH_FORCE_SYNC}}"
                    - name: "IMAGE_STREAM_REGISTRY"
                      value: "{{workflow.parameters.IMAGE_STREAM_REGISTRY}}"
                    - name: "IMAGE_STREAM_NAMESPACE"
                      value: "{{workflow.parameters.IMAGE_STREAM_NAMESPACE}}"
                    - name: "IMAGE_STREAM_TAG"
                      value: "{{workflow.parameters.IMAGE_STREAM_TAG}}"
